return {
  'Tummetott/unimpaired.nvim', -- Useful & comfy mappings for basic Vim commands
  dependencies = { 'folke/which-key.nvim' },
  event = 'VeryLazy',
  opts = {
    default_keymaps = true,
    keymaps = {
      previous = false,
      next = false,
      first = false,
      last = false,
      bprevious = { description = 'buffer' },
      bnext = { description = 'buffer' },
      bfirst = { description = 'First buffer' },
      blast = { description = 'Last buffer' },
      lprevious = { description = 'loclist' },
      lnext = { description = 'loclist' },
      lfirst = { description = 'First loclist' },
      llast = { description = 'Last loclist' },
      lpfile = { description = 'loclist file' },
      lnfile = { description = 'loclist file' },
      cprevious = { description = 'qflist' },
      cnext = { description = 'qflist' },
      cfirst = { description = 'First qflist' },
      clast = { description = 'Last qflist' },
      cpfile = { description = 'qflist file' },
      cnfile = { description = 'qflist file' },
      tprevious = { description = 'Matching tag' },
      tnext = { description = 'Matching tag' },
      tfirst = { description = 'First matching tag' },
      tlast = { description = 'Last matching tag' },
      ptprevious = { description = ':tprevious in preview' },
      ptnext = { description = ':tnext in preview' },
      previous_file = { mapping = '[F', description = 'Previous directory file' },
      next_file = { mapping = ']F', description = 'Next directory file' },
      blank_above = { description = 'Add blank line(s) above' },
      blank_below = { description = 'Add blank line(s) below' },
      exchange_above = { description = 'Exchange above line(s)' },
      exchange_below = { description = 'Exchange below line(s)' },
      exchange_section_above = { description = 'Move section up' },
      exchange_section_below = { description = 'Move section down' },
      enable_cursorline = false,
      disable_cursorline = false,
      toggle_cursorline = { description = 'cursorline' },
      enable_diff = false,
      disable_diff = false,
      toggle_diff = { description = 'diffthis' },
      enable_hlsearch = false,
      disable_hlsearch = false,
      toggle_hlsearch = { description = 'hlsearch' },
      enable_ignorecase = false,
      disable_ignorecase = false,
      toggle_ignorecase = { description = 'ignorecase' },
      enable_list = false,
      disable_list = false,
      toggle_list = { description = 'listchars' },
      enable_number = false,
      disable_number = false,
      toggle_number = { description = 'Line numbers' },
      enable_relativenumber = false,
      disable_relativenumber = false,
      toggle_relativenumber = { description = 'Relative numbers' },
      enable_spell = false,
      disable_spell = false,
      toggle_spell = { description = 'Spell check' },
      enable_background = false,
      disable_background = false,
      toggle_background = { description = 'Background' },
      enable_colorcolumn = false,
      disable_colorcolumn = false,
      toggle_colorcolumn = { description = 'colorcolumn' },
      enable_cursorcolumn = false,
      disable_cursorcolumn = false,
      toggle_cursorcolumn = { description = 'cursorcolumn' },
      enable_virtualedit = false,
      disable_virtualedit = false,
      toggle_virtualedit = { description = 'virtualedit' },
      enable_wrap = false,
      disable_wrap = false,
      toggle_wrap = { description = 'Line wrapping' },
      enable_cursorcross = false,
      disable_cursorcross = false,
      toggle_cursorcross = { description = 'cursorcross (x)' },
    },
  },
  config = function(_, opts)
    require('unimpaired').setup(opts)

    UTIL.register_keys { yo = 'toggle' }
  end,
}
